name: Docker CI

on:
  push:
    branches: [ main ]
  schedule:
    - cron: "23 13 3 * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_PLATFORMS: linux/amd64
    steps:
      - name: Docker Image Update Checker
        id: baseupdatecheck
        uses: lucacome/docker-image-update-checker@v1
        with:
          base-image: library/ubuntu:latest
          image: simeononsecurity/xmrig:latest
        if: github.event_name == 'schedule'

      - name: Checkout
        uses: actions/checkout@v3
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2.1.0
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: buildx
        with:
          install: true
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker image to DockerHub
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform $DOCKER_PLATFORMS -t simeononsecurity/xmrig:latest --progress=plain --push .
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT_TOKEN }}
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'

      - name: Build and push Docker image to GitHub Registry
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker buildx build --platform $DOCKER_PLATFORMS -t ghcr.io/simeononsecurity/xmrig:latest --progress=plain --push .
        if: github.event_name == 'push' || steps.baseupdatecheck.outputs.needs-updating == 'true'
